### ISSUE TITLE
What does filters social-share do ?

### ISSUE THREAD

**Issue by JauntyJJS** [schochastics/quarto-social-share#1]
Hi,

I managed to add the buttons to by Quarto post
https://jauntyjjs.github.io/Trelliscopejs_In_Quarto_Example/

However, I realised that the following Quarto YAML configuration is needed to make it work.

```r
filters:
  - social-share
```
This is also written on line 4 and 5 of your Quarto example as well.

Is it possible to explain what it does ?

Also, is it possible to add this information to the README as well if it is critical to make the share button icons appear ?

Thank you.

**Comment by mcanouil** [comment]
The Lua filter is required to process the YAML header, thus to display the share buttons.
It's indeed missing in the README, it's part of #2
