### ISSUE TITLE
How to share per post?

### ISSUE THREAD

**Issue by 0ptimista** [schochastics/quarto-social-share#11]
Share button shares the URL filled in `permalink`  parameters.

How to make share link automatic associate with every post?

**Comment by schochastics** [comment]
To the best of my knowledge, this is not possible yet. That is a feature that probably needs to be implemented into quarto directly

**Comment by 0ptimista** [comment]
> To the best of my knowledge, this is not possible yet. That is a feature that probably needs to be implemented into quarto directly

Thanks for answering!
