### ISSUE TITLE
Feature request: add button to post to Mastodon

### ISSUE THREAD

**Issue by znmeb** [schochastics/quarto-social-share#6]
As you may have heard, there's a migration from Twitter to Mastodon in progress. I would like to be able to add a "Post to Mastodon" on my posts similar to the "Post to LinkedIn" button I have now and the "Post to Twitter" that I used to have.

**Comment by schochastics** [comment]
@znmeb should be possible now

**Comment by znmeb** [comment]
Thanks!!
