### ISSUE TITLE
Share the current page? 

### ISSUE THREAD

**Issue by matiasandina** [schochastics/quarto-social-share#7]
I might have misunderstood this, but right now the buttons share one link, it would be nice to have the buttons share the current content and not a fixed one across posts.

**Comment by schochastics** [comment]
you can change the link for each of your posts to point to the current post. Just change
```yaml
share:
  permalink: "https://mr.schochastics.net/"
```
on each post

**Comment by matiasandina** [comment]
Yes, I understand this would be possible. I guess I was requesting for the links to be generated automatically for each post. My current approach is to have a `_metadata.yml` file that incorporates the social such that I don't have to do it for each post. See example [here](https://github.com/matiasandina/Webpage/blob/master/posts/_metadata.yml)

**Comment by schochastics** [comment]
I am afraid that this might not be possible. At least I have no idea where I would start with that. 

Maybe I still don't understand your question correctly but changing the permalink for each post is just a matter of charging on yaml entry in the post template?

**Comment by matiasandina** [comment]
Yes, understood. The only way to do this is to manually change the `share` for each post in the yaml header.
