### ISSUE TITLE
option to add buttons before-body

### ISSUE THREAD

**Issue by tashapiro** [schochastics/quarto-social-share#8]
Hi! This is an awesome extension. This is not an issue, perhaps more of a wish list item... is it possible to add a parameter to change the location of the social share icons to before-body?

**Comment by schochastics** [comment]
@tashapiro Thank you! I implemented the feature. Simply add `location: "before-body"` to the share metadata in the yaml header.

**Comment by tashapiro** [comment]
wow you are fast! just tried it out, this is MAGICAL. thank you!!

**Comment by tashapiro** [comment]
forgot to close out, thanks again :)
