### ISSUE TITLE
Container Class Feature Request

### ISSUE THREAD

**Issue by tashapiro** [schochastics/quarto-social-share#9]
Hi David, happy new year!

Really love this package for Quarto. The before-body add was fantastic, thank you.

I have another request. I'm trying to make some adjustments to align my icons to the left. But I notice because the parent div containing the social-share is "page-columns page-rows-contents page-layout-article" it automatically applies a grid that makes it difficult to align to the left.

Wondering if it would be possible to pass in a class name to the parameter to override the article grid class? Maybe there's a better way to approach this though. Attached samples of what I'm trying to do.

Thank you!

PS... as soon as Font Awesome comes out with a Buesky icon (next release) will be pestering you one last time with another wish list item. :) 

Current output:
<img width="861" alt="image" src="https://github.com/schochastics/quarto-social-share/assets/44143974/5682de99-8426-4436-b68a-e54c11649541">

Desired output:
<img width="840" alt="Screenshot 2024-01-08 at 11 43 54 AM" src="https://github.com/schochastics/quarto-social-share/assets/44143974/d56d12d3-d665-406d-83b1-00fb1fd4ba69">

**Comment by schochastics** [comment]
Hi Tanya, 
Happy new year!
I implemented it (I THINK...). I made some general changes to the `socia-share` class and added a parameter `divclass`.
If this parameter is present below share, it completely overrides the `page-columns page-rows-contents page-layout-article` part. It worked in my small test, but would appreciate some feedback from you, because I might have overlooked something

**Comment by schochastics** [comment]
@tashapiro did you have a chance to test it yet?

**Comment by arpita2512** [comment]
Hi @schochastics 
Thanks so much for this amazing extension!
I had the same issue and using `divclass` worked for me :)

**Comment by schochastics** [comment]
thanks for confirming!
